[package]
name = "arkana"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.17.1", default-features = false, features = [
    "std",
    "backend-linuxkms",
    "backend-winit-wayland",
    "renderer-femtovg",
    "compat-1-2"
] }
battery = "0.7.8"
gilrs = "0.11"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
libc = "0.2"
portable-pty = "0.9.0"
rodio = { version = "0.22.2", default-features = false, features = ["playback", "symphonia-mp3"] }

[build-dependencies]
slint-build = { version = "1.17.1" }
